server:
  port: 30000
spring:
  application:
    name: equipment-linkage-impl
  # mysql bruid配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.149:3306/equipment_linkage?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: user*2023
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 10000
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 1000
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      use-global-data-source-stat: true
      share-prepared-statements: true
      max-open-prepared-statements: 20

# mybatis配置信息
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  global-config:
    db-config:
      table-prefix: gp_
      id-type: auto
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

#logging:
#  level:
#    root: warn
#    com.txl.linkage.mapper: trace
# pattern:
#    console: '%p%m%n'